name: fingest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        pypy-version: ["pypy-3.9", "pypy-3.10", "pypy-3.11", "pypy-3.12", "pypy-3.13", pypy-3.14]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PyPy ${{ matrix.pypy-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pypy-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
